language: php
php:
  - nightly
  - hhvm
  - 7.1
  - 7.0
matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - composer require codeclimate/php-test-reporter:dev-master --dev
  - composer update --no-interaction --prefer-dist

script:
  - ./vendor/phpunit/phpunit/phpunit -v --coverage-clover build/logs/clover.xml

after_script:
  - CODECLIMATE_REPO_TOKEN=65f2616436b9bd5a63adc81451135ee71781af46e6c10132fadf219e97dcedbc ./bin/test-reporter
