sudo: false # @link https://docs.travis-ci.com/user/workers/container-based-infrastructure/

language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly

before_script:
  - if [[ $TRAVIS_PHP_VERSION =~ ^[0-9]+[.][0-9]+$ ]]; then phpenv config-rm xdebug.ini; fi
  - composer selfupdate
  - composer update --dev --no-interaction --prefer-source # source is required because of Doctrine ORM composer.json archive.exclude.tests directive and we need those...

script:
  - ./vendor/phpunit/phpunit/phpunit -v
